export const AppConfig = {
	site_name: 'NISHIDEMASAMI.GITHUB.IO',
	title: 'NISHIDEMASAMI.GITHUB.IO',
	description: '西出正美です。有益なことや無益なことなどいろいろ書いています。',
	url: 'https://nishidemasami.github.io',
	locale: 'ja',
	author: 'NISHIDE, Masami',
	copyright: '©NISHIDE, Masami Some Rights Reserved',
	pagination_size: 10,
	sidebar_links: [
		{ label: 'このサイトについて', path: '/about/' },
		{ label: 'ポートフォリオ', path: '/portfolio/' },
		{ label: '連絡フォーム', path: '/contact/' },
		// { label: 'Blog', path: '/blog/1/' },
	],
	contacts: {
		email: 'nishidemasami@gmail.com',
		facebook: 'masaminish',
		telegram: '',
		twitter: 'nishidemasami',
		github: 'nishidemasami',
		rss: '',
		vkontakte: '',
		linkedin: 'masami-nishide-66820bb2',
		instagram: 'nishidemasami',
		line: '',
		gitlab: '',
		weibo: '',
		codepen: '',
		youtube: '',
		soundcloud: '',
		medium: '',
	},
	amazon_affiliate_books: [
		{
			imgSrc: 'https://m.media-amazon.com/images/I/51vjj+osAgL._SL160_.jpg',
			title: 'プログラミングTypeScript...',
			url: 'https://www.amazon.co.jp/dp/4873119049?&linkCode=ll1&tag=nishidemasami-22&linkId=269abe7d00fb75538542192fd6ea40b4&language=ja_JP&ref_=as_li_ss_tl',
		},
		{
			imgSrc: 'https://m.media-amazon.com/images/I/51M44jPsASL._SL160_.jpg',
			title: 'プログラミングRust 第2版',
			url: 'https://www.amazon.co.jp/dp/4873119782?&linkCode=ll1&tag=nishidemasami-22&linkId=e2ff2c051967cc737eca98a12c4de66d&language=ja_JP&ref_=as_li_ss_tl',
		},
	],
};
