export const AppConfig = {
	site_name: 'NISHIDEMASAMI.GITHUB.IO',
	title: 'NISHIDEMASAMI.GITHUB.IO',
	description:
		'個人のブログです。有益なことや無益なことなどいろいろ書いています。',
	url: 'https://nishidemasami.github.io',
	locale: 'ja',
	author: 'NISHIDE, Masami',
	copyright: '©NISHIDE, Masami All rights reserved.',
	pagination_size: 10,
	sidebar_links: [
		{ label: 'このサイトについて', path: '/about/' },
		// { label: 'Blog', path: '/blog/1/' },
	],
	contacts: {
		email: 'nishidemasami@gmail.com',
		facebook: 'masaminish',
		telegram: '',
		twitter: 'nishidemasami',
		github: 'nishidemasami',
		rss: '',
		vkontakte: '',
		linkedin: 'masami-nishide-66820bb2',
		instagram: 'nishidemasami',
		line: '',
		gitlab: '',
		weibo: '',
		codepen: '',
		youtube: '',
		soundcloud: '',
		medium: '',
	},
};
